name: Feature request
about: Suggest a new feature or improvement
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: "Thanks for the idea. Please share context and desired outcome."
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: "Short description of the feature"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
    validations:
      required: false
